name: SATApp
options:
  bundleIdPrefix: com.latitudetechnolabs
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

targets:
  SATApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.latitudetechnolabs.satapp
        PRODUCT_NAME: "SAT App"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_BITCODE: "NO"
